### ISSUE TITLE
What's the planned compatibility with TypeDoc?

### ISSUE THREAD

**Issue by xmojmr** [aleksey-bykov/tstools#1]
Once the project's goal number 1 is achieved will it

1. replace the [Sebastian Lenz's TypeDoc](http://typedoc.io/) documentation generator tool
2. fix the [Typedoc incompatible with typescript 1.1](https://github.com/sebastian-lenz/typedoc/issues/38) problem
3. neither, its different project with different scope and different design goals

Which of the above is close to your plan?

**Comment by aleksey-bykov** [comment]
3. Neither. The goal is to give more convenient API to the code model (AST, and symbols).

Creating auto documentation based on the extract from the code model is just an immediate application.
